
# apiVersion: v1
# kind: Secret
# metadata:
#   name: mongo-secret
#   namespace: full-stack
# type: Opaque
# data:
#   mongo-username: c2h1YmhhbXNzYzEwMAo=
#   mongo-password: RWJGaURMY3pJYlMwbkpWZQo=
#   mongo-URL: bW9uZ29kYitzcnY6Ly9zaHViaGFtc3NjMTAwOkViRmlETGN6SWJTMG5KVmVAcHJvamVjdDAuZ3lzdHc4ci5tb25nb2RiLm5ldC9wcm9qZWN0MAo= 

# ---

# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: mongo-deployment
#   namespace: full-stack
# spec:
#   selector:
#     matchLabels:
#       app: mongodb
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: mongodb
#     spec:
#       containers:
#       - name: mongodb
#         image: mongo:6.0
#         ports:
#         - containerPort: 27017
#         env:
#         - name: MONGO_USERNAME
#           valueFrom:
#             secretKeyRef:
#               name: mongo-secret
#               key: mongo-username
#         - name: MONGO_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: mongo-secret
#               key: mongo-password
#         - name: MONGO_URL
#           valueFrom:
#             secretKeyRef:
#               name: mongo-secret
#               key: mongo-URL

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: database
#   namespace: full-stack
# spec:
#   ports:
#   - name: database
#     protocol: TCP
#     port: 27017
#     targetPort: 27017
#   clusterIP: None
#   selector:
#     app: database

# ---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: full-stack
spec:
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1    
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: shubhamshinde2206/crudbackend:latest
        ports:
        - containerPort: 5000
        

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: full-stack
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
