apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: full-stack
spec:
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1    
  replicas: 4
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: shubhamshinde2025/fullfrontend:v1
        ports:
        - containerPort: 5173
        env:
        - name: BACKEND_URL
          value: http://backend-service:5000

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: full-stack
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
 
